### ISSUE TITLE
[Bug] Backup doesn't work

### ISSUE THREAD

**Issue by Smile85363** [keshav-space/safenotes#66] opened 2022-11-09 20:50 UTC
It didn't work, neither in automatic mode nor when I tried to make it manually. I changed folders and backup locations, but nothing changes

**Comment by keshav-space** [comment] 2022-11-09 23:10
Few things needed
Device: ??
OS and Version:  ??
SafeNotes Version: ??
ScreenShot of Backup Page: ??

**Comment by landry314** [comment] 2022-11-10 00:23
I have the same problem and have discussed it a lot in issue #58. i wonder how many people are not able to backup. what operating system and version are you on?

**Comment by ghoevil** [comment] 2022-11-13 03:33
@keshav-space I also met the same bugs, no matter to use auto, or  backup now, or manual export.

**Comment by ghoevil** [comment] 2022-11-13 03:53
@keshav-space 

> You can see the photos as below. 

[![zFt3wj.jpg](https://s1.ax1x.com/2022/11/13/zFt3wj.jpg)](https://imgse.com/i/zFt3wj)

[![zFtM6S.jpg](https://s1.ax1x.com/2022/11/13/zFtM6S.jpg)](https://imgse.com/i/zFtM6S)

[![zFtuSf.jpg](https://s1.ax1x.com/2022/11/13/zFtuSf.jpg)](https://imgse.com/i/zFtuSf)

**Comment by landry314** [comment] 2022-11-13 09:37
even though i disabled secure display, still screenshots are just black. i cant show you. nothing happens. no backup is ever made. it was made in version 1.0. i still have a "vault" file from then.

**Comment by ghoevil** [comment] 2022-11-13 14:05
@landry314 You have to Kill it  from the background run after disable,and re-open the app. It will be able to let you make screenshot.

**Comment by keshav-space** [comment] 2022-11-13 22:11
The v2.0.2-beta release out and it should fix this issue. 
**_Do test this out and let me know if it's working_**. [safenotes-v2.0.2-beta.apk](https://github.com/keshav-space/safenotes/releases/download/v2.0.2-beta/safenotes-v2.0.2-beta.apk)

# What was causing backup and export to fail?
After doing some research on this it turns out that to store files in generic `user-desired locations` or to do `backups` the app needs to have MANAGE_EXTERNAL_STORAGE permission.  

> it was made in version 1.0. i still have a "vault" file from then.

In v1.0 export were directly saved in the download folder which is accessible by apps without using MANAGE_EXTERNAL_STORAGE permission. 
But to save files anywhere outside `app-specific storage space` is not consistently possible without MANAGE_EXTERNAL_STORAGE, for some OS it might work for some it might not and that is expected behavior.

Moreover, for the backup to work - the same backup file is periodically updated which is not possible with novice `create document intent`

> Note: ACTION_CREATE_DOCUMENT cannot overwrite an existing file. If your app tries to save a file with the same name, the system appends a number in parentheses at the end of the file name.
> 
> For example, if your app tries to save a file called confirmation.pdf in a directory that already has a file with that name, the system saves the new file with the name confirmation(1).pdf.

References

- https://developer.android.com/training/data-storage#permissions
- https://developer.android.com/training/data-storage/shared/documents-files#create-file

**Comment by landry314** [comment] 2022-11-14 04:31
Well, what you could do, is maintain a few versions of backups for x days, labeling them with their date then delete the oldest backup while replacing it with the newest. This is good in case the user makes a mistake deleting data and solves the file naming problem above.

I am still stuck on the fdroid signature version or I would beta test.

I tried selecting the /Download folder but it won't let me which is funny because in version 1.0 that was the ONLY option. It will let me choose any other folder on /sdcard/ which is not protected space but it wont actually write to it...

**Comment by landry314** [comment] 2022-11-14 04:36
Oh, good news, I was able to create a folder INSIDE /Download and create a backup file there. The Auto Backup feature is working in there too!

**Comment by ghoevil** [comment] 2022-11-14 05:28
@keshav-space just test the beta, doesn't work. 

![img](https://23img.com/i/2022/11/14/lu5vby.gif)

**Comment by keshav-space** [comment] 2022-11-14 11:50
@ghoevil, please share the os and version.

**Comment by keshav-space** [comment] 2022-11-14 12:06
> Well, what you could do, is maintain a few versions of backups for x days, labeling them with their date then delete the oldest backup while replacing it with the newest. This is good in case the user makes a mistake deleting data and solves the file naming problem above.

The problem I discussed earlier can only be addressed by MANAGE_EXTERNAL_STORAGE permission. Without it, application can not `modify or delete or replace` an existing file irrespective of which app created it.

**Comment by ghoevil** [comment] 2022-11-14 12:55
@keshav-space I'm using Huawei P40,and os is Harmony OS 2.0.0.276.

**Comment by keshav-space** [comment] 2022-11-17 04:12
# Update

In the last few days, I have extensively read about android's migration towards more privacy-friendly Android APIs.
## Below is a brief summary of how that impacts storage access
### Android >= 11
**No Storage Permission** : Apps can create new files in the download folder without permission
**Media and File Permission** : Apps can `read` media and files but can't modify or create files except in `app-specific storage space` [ _moreover, the android will never expose the actual file location rather a cached file location is shared with apps_]
**All File Permission** : When `MANAGE_EXTERNAL_STORAGE` permission is granted, app can `read/modify/create/delete` files in external shared storage.

### Android < 11
**No Storage Permission** :  App can not access any part of external shared storage
**File Permission** : App can read, modify, create and delete files in external shared storage.

## How Safe Notes will handle the storage access?
These access control will become more stringent in the coming year, something similar to iOS, and that's good for user privacy. Bottom line is that apps should not use `All file Permission` unless absolutely needed. 
Safe Notes will not use `All File Permission`, this means that users will not be able to choose the location of their choice for backup. Backup will be made inside the Download directory within the Safe Notes folder. [See videos below ]

@landry314 This will also resolve the issue you raised here https://github.com/keshav-space/safenotes/issues/60, auto backup and manual export is merged.
With fewer nobs and dials, backup looks much simpler and more intuitive.

@ghoevil though I haven't been able to test new feature on  Harmony OS I'm sure it will work there too.

## The new feature is tested on Android 12, 11, 10, 9, 8.1, 8.0 and 7.1
Android 12 | Android 12 | Android 11 | Android 10
:-: | :-: | :-: | :-:
|<video src='https://user-images.githubusercontent.com/44315208/202319781-ed545d9d-a6b0-4ecd-8e80-2937a5f27e18.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/44315208/202320758-4bcb0ff7-78da-4d2d-9053-75d44841e647.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/44315208/202323296-8b8fdad9-70c9-4541-a569-46cda0a042ff.mp4' width=180/>| <video src='https://user-images.githubusercontent.com/44315208/202323301-476e781d-e567-436d-8c51-7c5f50170aae.mp4' width=180/>|
Android 9 | Android 8.1 | Android 8.0 | Android 7.1
|<video src='https://user-images.githubusercontent.com/44315208/202323303-be734954-9482-40cd-b678-22d6cbcd43f0.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/44315208/202323309-f1345990-4737-4aa6-9a4f-4d133a7fd933.mp4' width=180/> | <video src='https://user-images.githubusercontent.com/44315208/202323311-65621b08-ea3e-4b8e-b423-b689c7060c57.mp4' width=180/>| <video src='https://user-images.githubusercontent.com/44315208/202323316-91642b7b-5a76-442d-9d5b-42c733cff962.mp4' width=180/>|

**Comment by ghoevil** [comment] 2022-11-19 06:04
@keshav-space yes good, now backup works well on the beta ver. , but the language cannot be clicked with no response.

**Comment by landry314** [comment] 2022-11-19 09:04
you could also make the backup path:

/storage/emulated/0/Android/data/com.trisven.safenotes/files/Backup/

this makes it harder for the user to find the file but would require no extra permissions i believe.

**Comment by keshav-space** [comment] 2022-11-19 13:19
>  but the language cannot be clicked with no response.

The language setting is already added and will be fully functional on the next release i.2. v2.1.0



> you could also make the backup path:
> 
> /storage/emulated/0/Android/data/com.trisven.safenotes/files/Backup/

- Users won't be able to easily find the backup file while changing the device. 
- Since that's Safe Notes' app-specific folder user won't be able to couple the backup with other tools like SyncThing

**Comment by keshav-space** [comment] 2022-11-19 19:52
https://github.com/keshav-space/safenotes/releases/tag/v2.1.0

**Comment by keshav-space** [comment] 2022-11-24 07:21
closing this issue since this was addressed with the new release v2.1.0 https://github.com/keshav-space/safenotes/releases/tag/v2.1.0

**Closed by keshav-space** 2022-11-24 07:21 UTC
Labels: enhancement
