### ISSUE TITLE
Import failing for unencrypted data

### ISSUE THREAD

**Issue by samar0011** [keshav-space/safenotes#3] opened 2022-03-20 17:09 UTC
Data import for unencrypted data is failing.
Device: Samsung a21s
Android version: 11

**Comment by keshav-space** [comment] 2022-05-18 10:29
@BiosCandy I was able to reproduce the problem. It seems like the problem is due to unescaped newline in the `description` section of JSON data. It can also fail if there are void characters in the JSON file. IMO renormalizing the file before import would be the best solution for it. Anyways we will issue the fix soon.

**Comment by keshav-space** [comment] 2022-09-30 21:33
Fixed in https://github.com/keshav-space/safenotes/commit/c8179af8684a864cf4d2003f19c52978a606458f

**Closed** 2022-09-30 21:34 UTC
Labels: bug
